export const actionTypes = {
	SET_WALLETS: 'SET_WALLETS',
	UPDATE_PROVIDER: 'UPDATE_PROVIDER',
	UPDATE_BLOCKHEADER: 'UPDATE_BLOCKHEADER',
	UPDATE_PEERCOUNT: 'UPDATE_PEERCOUNT',
	UPDATE_CURRENCY_UNIT: 'UPDATE_CURRENCY_UNIT',
	UPDATE_CONNECTED_NETWORK: 'UPDATE_CONNECTED_NETWORK',
}