export const actionTypes = {
	UPDATE_EXCHANGE_RATES: 'UPDATE_EXCHANGE_RATES',
	CRYPTO_COMPARE_CONNECTED: 'CRYPTO_COMPARE_CONNECTED', 
	UPDATE_ETHER_PRICES: 'UPDATE_ETHER_PRICES',
	SET_SELECTED_WALLET: 'SET_SELECTED_WALLET',
	SET_WALLETS: 'SET_WALLETS',
	UPDATE_PROVIDER: 'UPDATE_PROVIDER',
	UPDATE_BLOCKHEADER: 'UPDATE_BLOCKHEADER',
	UPDATE_PEERCOUNT: 'UPDATE_PEERCOUNT',
	UPDATE_CURRENCY_UNIT: 'UPDATE_CURRENCY_UNIT',
	UPDATE_CONNECTED_NETWORK: 'UPDATE_CONNECTED_NETWORK',
}